server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/pizzadb
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Включаем автоматическую загрузку data.sql
spring.sql.init.mode=always
# (Для более старых версий Spring Boot бывает нужно использовать:
#  spring.datasource.initialization-mode=always )

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Security
spring.security.user.name=admin
spring.security.user.password=admin

logging.level.org.springframework.sql=DEBUG
logging.level.org.springframework.jdbc=DEBUG
