server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/pizzadb
spring.datasource.username=postgres
spring.datasource.password=1234

# Hibernate DDL-auto: update (НЕ удаляет таблицы при рестарте,
#   сохраняет данные)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Не нужно schema.sql/data.sql при каждом старте,
#   но если хотите, можно подключить data.sql ТОЛЬКО для первоначальных данных
spring.sql.init.mode=never

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Security
spring.security.user.name=admin
spring.security.user.password=admin

logging.level.org.springframework.sql=DEBUG
logging.level.org.springframework.jdbc=DEBUG
